name: ProteGO
attributes:
  ORGANIZATIONNAME: GOV

options:
  minimumXcodeGenVersion: 2.13.1
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "12.0"
  preGenCommand: sh scripts/generateProject.sh
  postGenCommand: pod install

configs:
  Debug_dev: debug
  Debug_stg: debug
  Debug_prod: debug
  Release_dev: release
  Release_stg: release
  Release_prod: release

settings:
  configs:
    Debug_dev:
      PRODUCT_BUNDLE_IDENTIFIER: pl.gov.mc.protego.dev
      PROVISIONING_PROFILE_SPECIFIER: match Development pl.gov.mc.protego.dev
    Release_dev:
      PRODUCT_BUNDLE_IDENTIFIER: pl.gov.mc.protego.dev
      PROVISIONING_PROFILE_SPECIFIER: match AdHoc pl.gov.mc.protego.dev
    Debug_stg:
      PRODUCT_BUNDLE_IDENTIFIER: pl.gov.mc.protego.stg
      PROVISIONING_PROFILE_SPECIFIER: match Development pl.gov.mc.protego.stg
    Release_stg:
      PRODUCT_BUNDLE_IDENTIFIER: pl.gov.mc.protego.stg
      PROVISIONING_PROFILE_SPECIFIER: match AppStore pl.gov.mc.protego.stg
    Debug_prod:
      PRODUCT_BUNDLE_IDENTIFIER: pl.gov.anna.prod
      PROVISIONING_PROFILE_SPECIFIER: match Development pl.gov.anna.prod
    Release_prod:
      PRODUCT_BUNDLE_IDENTIFIER: pl.gov.anna.prod
      PROVISIONING_PROFILE_SPECIFIER: match AppStore pl.gov.anna.prod

schemes:
  ProteGO_dev:
    build:
      targets:
        ProteGO: all
    test:
      config: Debug_dev
      gatherCoverageData: true
      coverageTargets:
      - ProteGO
      targets:
        - name: ProteGOTests
  ProteGO_stg:
    build:
      targets:
        ProteGO: all
    test:
      config: Debug_dev
      gatherCoverageData: true
      coverageTargets:
      - ProteGO
      targets:
        - name: ProteGOTests
  ProteGO_prod:
    build:
      targets:
        ProteGO: all
    test:
      config: Debug_dev
      gatherCoverageData: true
      coverageTargets:
      - ProteGO
      targets:
        - name: ProteGOTests
targets:
  ProteGO:
    templates:
      - Application
    settings:
      base:
        DEVELOPMENT_TEAM: MT2B94Q7N6
        CODE_SIGN_STYLE: Manual

  ProteGOTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    directlyEmbedCarthageDependencies: false
    sources:
    - path: ProteGOTests
      includes:
        - "**/*Mock.swift"
    - path: ProteGO
      includes:
        - "**/*Specs.swift"
        - "**/Data+HexString.swift"
    dependencies:
      - target: ProteGO
      - carthage: Quick
      - carthage: Nimble
    postBuildScripts:
      - script: /usr/local/bin/carthage copy-frameworks
        name: Carthage

targetTemplates:
  Application:
    type: application
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: ProteGO/Info.plist
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.development
    dependencies:
      - carthage: Lottie
      - carthage: Swinject
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: SnapKit
      - carthage: SwiftTweaks
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: Reachability
      - carthage: Valet
    configVariants:
      - Debug_dev
      - Debug_stg
      - Debug_prod
      - Release_dev
      - Release_stg
      - Release_prod
    sources:
    - path: ProteGO
      excludes:
        - "**/*Specs.swift"
        - "**/*Mock.swift"
    postCompileScripts:
      - script: |
                ${PODS_ROOT}/SwiftLint/swiftlint lint --strict
                exit $?
        name: Swiftlint
    postBuildScripts:
      - script: /usr/local/bin/carthage copy-frameworks
        name: Carthage
    postBuildScripts:
      - script: |
                if [ "$CRASHLYTICS_ENABLED" == "true" ]; then
                  ${PODS_ROOT}/FirebaseCrashlytics/run
                fi
        name: Crashlytics
